# Kubernetes production overlay

app:
  baseUrl: ${APP_BASE_URL}

backend:
  baseUrl: ${BACKEND_BASE_URL}
  cors:
    origin:
      - ${APP_BASE_URL}
      - ${BACKEND_BASE_URL}

auth:
  environment: production
  experimentalExtraAllowedOrigins:
    - ${APP_BASE_URL}
    - ${BACKEND_BASE_URL}
