apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: wake-on-lan
  title: Wake up a Physical Machine
  description: Uses WOL to turn on a physical machine
spec:
  owner: group:platform-team
  type: infrastructure

  parameters:
    - title: Machine ID
      required:
        - id
      properties:
        id:
          title: Machine ID
          type: string
          description: Unique VM name
          ui:autofocus: true
          enum:
            - windows-01
            - SNPS Laptop

  steps:
    - id: send-wol
      name: Send Power On Request
      action: webhook:wol
      input:
        app: infra
        event: wol
        id: ${{ parameters.id }}
        metadata:
          requestedBy: ${{ user.entity.metadata.name }}

  output:
    links:
      - title: Webhook Endpoint
        url: ${{ steps['send-wol'].output.targetUrl }}
      - title: Request Resource URL
        url: ${{ steps['send-wol'].output.resourceUrl }}
    text:
      - title: VM Request Result
        content: |
          Status: ${{ steps['send-wol'].output.status }}
          Response: ${{ steps['send-wol'].output.response }}